version: "3.8"

services:
  app:
    container_name: google-books
    image: google-books
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
